indent-width = 4
line-length = 100
target-version = "py311"

exclude = [
    "*/migrations/*",
    "/site",
    ".DS_Store",
    ".eggs",
    ".git",
    ".hg",
    ".hypothesis",
    ".idea",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pybuilder",
    ".pytest_cache",
    ".pyre",
    ".pytype",
    ".ropeproject",
    ".scrapy",
    ".svn",
    ".tox",
    ".venv",
    ".venv*",
    ".venv_*",
    ".webassets-cache",
    "__pycache__",
    "__pypackages__",
    "build",
    "cover",
    "CVS",
    "develop-eggs",
    "dist",
    "docs/_build",
    "downloads",
    "eggs",
    "htmlcov",
    "instance",
    "lib",
    "lib64",
    "migrations",
    "node_modules",
    "parts",
    "profile_default",
    "sdist",
    "share/python-wheels",
    "target",
    "tmp/cache",
    "var",
    "venv",
    "venv*",
    "venv_*",
    "venv.bak",
    "wheels",
]

[lint]
select = ["ALL"]
ignore = [
    "A003",
    "ANN002",
    "ANN003",
    "ANN201",
    "ANN202",
    "ANN204",
    "ANN205",
    "ANN206",
    "ANN401",
    "BLE001",
    "C901",
    "COM812",
    "D100",
    "D101",
    "D102",
    "D103",
    "D104",
    "D105",
    "D106",
    "D107",
    "D202",
    "D203",
    "D205",
    "D211",
    "D212",
    "D213",
    "D400",
    "D401",
    "D406",
    "D407",
    "D415",
    "D417",
    "ERA001",
    "FBT001",
    "FBT002",
    "G004",
    "I001",
    "INP001",
    "PLR0913",
    "PLR0915",
    "PLR2004",
    "PLW2901",
    "PT019",
    "PTH123",
    "RUF012",
    "Q000",
    "Q003",
    "S301",
    "S311",
    "S603",
    "SLF001",
    "T201",
    "UP015",
    "UP035",
]
fixable = ["ALL"]
unfixable = []
per-file-ignores = {}
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[format]
quote-style = "single"
indent-style = "space"
skip-magic-trailing-comma = true

[lint.isort]
known-first-party = ["system", "app"]

[lint.mccabe]
max-complexity = 6
